### ISSUE TITLE
Get "LastModifiedTime" for contacts?

### ISSUE THREAD

**Issue by rw268** [jamesiarmes/php-ews#130]
Hi, I'm new to php-ews, which seems to be a great library.
I played already with the Wiki examples, so far everything is clear.

However, if I use the "Contact: Get List" or "Contact: Get Details" scripts, I would like to get the "LastModifiedTime" parameter returned by the Exchange server for each item.

Can anybody please give me a hint, how to solve this?
Many thanks in advance!
Regards, Reini

**Comment by jamesiarmes** [comment]
This should be as simple as iterating over the contacts and accessing the `LastModifiedTime` property on each. You should be able to pass the value to a new `DateTime` object in order to more easily work with this value in PHP.

This issue is over three years old. If you continue to have trouble with the latest version from master, please open a new issue.
