### ISSUE TITLE
Output XML Raw request for debug reason?

### ISSUE THREAD

**Issue by yu0307** [jamesiarmes/php-ews#266]
Hi, I just wondering if there is a option to ouput the REST/Soap request as XML for debugging purpose? so that we know what kind of data are we sending over.
thank you

**Comment by jamesiarmes** [comment]
With 4e682a9995af3fbf3989bc4ebf783cc549bf661d, you can now get the actual `SoapClient` object used in a request by calling `Client::getClient()`. You will also need to ensure your version of php-ntlm has been updated as jamesiarmes/php-ntlm@8ac27971a5d345e780239e850977c86b2dbeebf2 resolves an issue where calling `SoapClient::__getLastResponse()` would return `null` rather than the raw XML response.
