### ISSUE TITLE
Supported versions of Exchange

### ISSUE THREAD

**Issue by turumart** [jamesiarmes/php-ews#271]
Hi,
is exchange 2013 supported by  php-ews?
I'm creating a web application connected to an exchange 2007 server.
Soon the the server will be replaced with a 2013 version.
The scripts created for 2007 version will be ok for 2013 version?

Regards

**Comment by Demonslay335** [comment]
I've been able to send through Exchange 2013 on our network. I think one caveat was I had to explicitly set the version to 2010 SP2, since the class will default back to 2007 if it doesn't detect the version right.

`$ews = new ExchangeWebServices(EXCHANGE_SERVER, EXCHANGE_USER, EXCHANGE_PASS, ExchangeWebServices::VERSION_2010_SP2);`

I've also had some issues with connecting to AutoDiscover, but I don't know if that is just based on our domain setup.

Also, definitely make sure your cURL version is up to par with the required version in the readme, otherwise NTLM authentication will fail for sure.
