### ISSUE TITLE
Connecting to Office 365

### ISSUE THREAD

**Issue by keithslater** [jamesiarmes/php-ews#273]
Hello, previously I have used php-ews with regular Exchange Servers. Now I want to connect to an Office 365 server however the server is Small Business Premium.

What is the best way to create a user in Office 365 so that it can manage everyone's calendars and emails? I have read that impersonation is the best way but I can't do that with Small Business Premium. Should I create a delegate admin? Would that even work?

Thanks

**Comment by Demonslay335** [comment]
Impersonation is definitely the best way to go, and I think that might be the way of least resistance. But, if you don't have a way to set that up without upgrading, you can certainly try delegation. I think Delegation is supposed to only be for a user managing their own mailbox, and allowing the system their privileges; think of it like accessing webmail, you only give the application permission to use your credentials to access your own stuff.

I've not personally messed with delegation since my requirements lead to impersonation (much more control on everything, don't have to setup explicit permissions for each user). This may especially be a problem if you wish for the app to send emails for the user, as I believe delegation will act as "on behalf of" instead of, well, impersonating the user.

**Comment by jamesiarmes** [comment]
@Demonslay335 assessment is correct. Delegation is intended to allow users to giver other users permissions to perform certain actions within their mailbox, such as an assistant or a co-worker when the user is on vacation.

If you can't use impersonation, the only real alternative is to maintain a list of user credentials that you can use for connecting to each user. If you're going this route, be sure to encrypt any passwords that you are storing.
