### ISSUE TITLE
Exchange Web Services PHP - SOAP client returned status of 401

### ISSUE THREAD

**Issue by lucasperon** [jamesiarmes/php-ews#291]
Hello Mr Armes,

I used your "Exchange Web Services PHP" script since few month, this working well until recently.
I have an issue now, I think the exchange service I use (Exchange 2010)  has been migrated
so I have updated the directory "php-ews-master" ( as you said in a post ) on my server with your latest version: "https: // github.com/jamesiarmes/php-ews "but it still is not working.

Here is the error I when running the scipt
I do not find a solution to solve this problem.

<b>Fatal error</b>:  Uncaught exception 'EWS_Exception' with message 'SOAP client returned status of 401' in /php-ews-master/ExchangeWebServices.php:1221
Stack trace:
#0 /php-ews-master/ExchangeWebServices.php(547): ExchangeWebServices-&gt;processResponse(NULL)
#1 sync-planning.php(59): ExchangeWebServices-&gt;FindItem(Object(EWSType_FindItemType))
#2 {main}

  thrown in <b>/php-ews-master/ExchangeWebServices.php</b> on line <b>1221</b><br />

Could you help me ?
Thank you and best regards.
Lucas

**Comment by MrDru** [comment]
Hi Lucas,

the error code (`401`) you get means `Unauthorized`. It seems that your URI, username and/or password is/are wrong.

Best regards.

**Comment by guerriky** [comment]
Hi Lucas,
sometimes I get the error, too.
It's mostly just the server that got somehow tired of my requests, and thus returns unauthorized for no apparent reason.

I just set up an exception handling system, and caught them when they are launched. Then try again.

This works most of the time.

MrDru, when I (or our users) misspell something in the connection string, the server does not return an error.
In fact, it returns a cURL 52, empty response.

I get 401 as a response usually during an elaboration with many calls. 
Some of them fail, but if you retry them, they fail no more (if you capture the exception, obviously).

**Comment by lucasperon** [comment]
Hi, 
My Internet supplier reset the account password ! Thx for your help, i'm confused.
By the way anyone have a PHP example script to synchronize exchange account email with a MySQL database ?
Thank you.
Best Regards.

**Comment by Garethp** [comment]
@lucasperon 

Hi Lucas. It seems that Exchange may have an API limit detection on it. IE: If you try to make too many requests, it might lock your account temporarily. Maybe see if you can contact your host to get it raised? Note: This is pure speculation, I could be wrong.

As for synchrnoising your exchange account, I don't have any examples of implementations, but I can point you in the direction of where to look. For starters, take a look at the EWS Documentation for [Syncing Items](https://msdn.microsoft.com/en-us/library/office/dn440953(v=exchg.150).aspx#bk_ewsexamplea). Basically, it'll let you get a list of *changes* since the last time you checked and you can then act on those changes (use them to update MySQL for example).

Likewise, I've made it slightly easier in my fork of this library, and you can look at how I did it [here](https://github.com/Garethp/php-ews/blob/master/src/API.php#L284). Don't take that as foolproof though, as I only *know* it works for CalendarItems, but it might give you an idea of how to implement it yourself.

Likewise, this is a feature I'll be introducing in to my library in the coming week if you can wait

Thanks, Gareth

**Comment by Geoffry304** [comment]
did send a mail
