### ISSUE TITLE
retrieve Calendar Events with impersonation?

### ISSUE THREAD

**Issue by rogatec** [jamesiarmes/php-ews#330]
> Probably not a bug - but a _question_

Hi,

I'm trying to implement the wiki entry [Calendar:Get List](https://github.com/jamesiarmes/php-ews/wiki/Calendar:-Get-List-(Retrieving-Id-and-ChangeKey)).

But unfortunately my connection to the ews server is made via an impersonation account and therefore from this user, the calendar is empty.

Is there a possibility to retrieve all events from the ews server _between a date_ while connected via an impersonation account?

### Background
- The customer wants that his users can view their operations in Outlook as calendar entries.
- Additionally to verify the matching between our system and the outlook entries, the informations are stored in a MySQL database (with both Outlook keys).
- Inserting, deleting and updating is working fine via an impersonation, but if a Outlook user changes an entry manually (e.g. adding some body text) an update from our system fails, because the _changeKeyOutlook_ has changed.

Therefore I'm trying to achieve with this _retrieveEvents_ method to check wether a user has manipulated the outlook entry manually in Outlook (which he is not allowed, but we need a double check) and if so I'm overwriting it with the information I stored in the MySQL database.

### Reflections
- To set an impersonation I need the mail address from the user.-> Do I need to loop through all _valid_ exchange addresses? How can I get them?

#### Any hints are very appreciated

Below you can see the method, which is obviously quite the same from your wiki entry.    
```php
/**
* retrieve all outlook events between a timeframe - used for sync mechanic
*
* @param string $startTime formatted string: Y-m-d H:i:s
* @param string $endTime formatted string: Y-m-d H:i:s + 31536000 (1 year)
*
* @return \phpews\EWSType_CalendarItemType
*
* @throws \phpews\EWS_Exception
*/
public function retrieveEvents($startTime, $endTime)
{
    $request = new phpews\EWSType_FindItemType();
    $request->Traversal = phpews\EWSType_ItemQueryTraversalType::SHALLOW;
   
    $request->ItemShape = new phpews\EWSType_ItemResponseShapeType();
    $request->ItemShape->BaseShape = phpews\EWSType_DefaultShapeNamesType::DEFAULT_PROPERTIES;
    
    $request->CalendarView = new phpews\EWSType_CalendarViewType();
    $request->CalendarView->StartDate = date('c', strtotime($startTime));
    $request->CalendarView->EndDate = date('c', strtotime($endTime));
    
    $request->ParentFolderIds = new phpews\EWSType_NonEmptyArrayOfBaseFolderIdsType();
    $request->ParentFolderIds->DistinguishedFolderId = new phpews\EWSType_DistinguishedFolderIdType();
    $request->ParentFolderIds->DistinguishedFolderId->Id = phpews\EWSType_DistinguishedFolderIdNameType::CALENDAR;
    
    $response = $this->ews->FindItem($request);

    if ($response->ResponseMessages->FindItemResponseMessage->ResponseClass != "Success") {
        throw new \phpews\EWS_Exception("No events were found in Outlook between the timeframe: " .
            $startTime . " - " . $endTime);
    }

    return $response->ResponseMessages->FindItemResponseMessage->RootFolder->Items->CalendarItem;
}
```

**Comment by Garethp** [comment]
Hi there

That's a... very interesting use case. I'm going to split this up in to multiple parts. First, a preface though. The library that you're using is outdates and unmaintained. I don't think you're going to get a response from the creators on how to solve your question. I've made my own library, [`garethp/php-ews`](http://github.com/Garethp/php-ews) that I recommend you move over to. It's maintained, I help out in the issues section, it's PSR-4 compatible and much simpler to use. Any answers I give here will either be abstract or related to my library. They should still work, I just can't give you concrete code examples.

### Not being able to update because the ChangeKey has changed
Okay, this is the easier problem to tackle. For a very simple solution, you can just do a `GetItem` request with only the ID, emitting the ChangeKey, and it'll provide you with the latest instance of the ChangeKey. This would be useful for first checking if you're in sync and if you're not still being able to edit the item. It would not fix the issue of a user changing the event on Exchange

### Getting a list of Changes
There's a `SyncFolderItems` call that will retrieve a list of events for you that you might be interested in. If you call it the first time, without a SyncState, it'll pass you back the first `x` events (From the start of the folder I believe) as well as a `SyncState`. Passing this `SyncState` in to subsequent calls will pass you a list of events **since** then as well as a new `SyncState`. So you can use this always get the events that have occurred **since you last checked**.

### Getting all Changes for All Users
This is where the solutions that I can think of aren't as clean. The only way I *know* how to use would be to set up a cron job and do a loop over all users to make a check. I don't know how to get a list of all valid users, but I would suggest you don't have to. You have a list of all users that are using this application in your DB, yes? You must also have email addresses for them, so that you can impersonate them. I'd suggest using this list from your DB rather than querying for a list of all users.

There *might* be another way. I have no experience with it, and I don't know how easy or hard it is to implement in PHP, but Microsoft offers a way to [subscribe to event notifications](https://msdn.microsoft.com/en-us/library/office/dn458791(v=exchg.150).aspx). You can set this up to get push notifications. This might be the solution you're after, but I have no experience with it

**Comment by rogatec** [comment]
Well,

Thank you very much for the quick response and the very exhaustive information!

I'll consider refactoring the current library implementation to move to your fork. Great to see the PSR-4 standard, even if the customer system is running on an old ZF1 without namespacing etc. ;-)

The part with the `GetItem` ist a great hint, therefore I can loop through my DB entries (I also have the mail address of the user in a column as you guessed) and can validate the `changeKey`.

Additionally this `SyncFolderItems` sounds quite useful, I'll dig into it.

Lastly your guessing is right. I will not ask the exchange server to give me the mail addresses but our system itself (I always need to, because there are some users with mail addreses which don't exist - freelance collaborators..)

Again thanks for your response!
> Might be a day saver

**Comment by Garethp** [comment]
You should still be able to use ZF1 with Composer, I believe. In fact, you could most likely register ZF1 in composer as a PSR-0 namespace and let Composer do the actual autoloading. If you do end up migrating, here's where I host [`examples`](https://github.com/Garethp/php-ews/tree/master/examples), they should be helpful. Likewise, unless you specify which version of Exchange you're using, this library will default to using the Exchange 2007 version (Which is just a header set in the calls for backwards compatibility), while mine defaults to Exchange 2010. This mostly isn't an issue, but if you don't set it to Exchange 2007 in my library, your stored ID's will be rejected (ID Formats changed). If you go forward and want to convert your stored ID's to 2010 ID's, [here's how to make the conversion](https://github.com/Garethp/php-ews/blob/master/examples/basic/convertItemIdFormat.php). You should only have to run that once on each ID and store the new format.

Good luck on your solution
