### ISSUE TITLE
Updated schema definitions

### ISSUE THREAD

**Issue by jamesiarmes** [jamesiarmes/php-ews#341]
The XSD files for the library are severely outdated, but I don't have access to a recent version of Exchange. If anybody is running the latest release of Exchange 2013, I could really use a copy of your schema files. See https://msdn.microsoft.com/en-us/library/office/aa580675(v=exchg.150).aspx for more information on how to obtain them from your server.

**Comment by Garethp** [comment]
Hm, sadly I don't have access to a 2013 server any more, but I'm going to keep an eye on this issue. If it's closed before I can find a Schema, I'll also try and integrate it in to my own ews library, if I can get hold of the Schema before then I'll share it here

**Comment by Garethp** [comment]
That being said, I've asked the maintainer of [this](https://github.com/WsdlToPhp/PackageEws365/issues/3) library if I can use his Schema, which is relatively up to date. I wouldn't expect further schemas to pop up though, from my understanding there's not much active development for EWS at Microsoft any more

**Comment by jamesiarmes** [comment]
I have recently gained access to an Exchange Online subscription which I believe I will be able to utilize in order to retrieve the updated files.

**Comment by Garethp** [comment]
Version 1.0? I take it then that you intend to take this package out of it's current abandoned state?

**Comment by jamesiarmes** [comment]
This package was never truly abandoned, my time was severely limited until recently, but I have been actively working on this new version for quite some time.

**Comment by Garethp** [comment]
Gotcha. Well, I think I've made some good improvements on what was originally a fork of this over at [`garethp/php-ews`](http://github.com/Garethp/php-ews) that you might consider bringing in. Major Improvements in my opinion are

 * Autogenerated classes that use getters and setters instead of property access
 * Classmap in the SoapCall that means that the result comes in the right classes (This is autogenerated too)
 * Building items from an array
 * Guzzle as the means of HTTP Calls
 * Configurable authentication method
 * Response filtering to bring the mostly relevant information
 * Simplified API usage for some use cases

There's a tonne of other improvements as well, but those are just the highlights

**Comment by jamesiarmes** [comment]
This has been completed with 2c4e30c0fdd7084e3d7460ea9d463f7a89d23eed.
